langchain-ai/langsmith-docs

- docs/tracing/tracing-faq.mdx
@nfcampos @hinthornw.
Unlike Python, callbacks in JS block by default: 
https://js.langchain.com/docs/modules/callbacks/how_to/background_callbacks
> Update callback docs to reflect proper JS behavior

- src/components/Hub.js
`langchainhub` is now a hard dependency and no longer needs to be installed separately.
> Remove langchainhub install requirement from JS docs

- docs/tracing/tracing-faq.mdx
- src/components/QuickStart.js
Reduce confusion since you want callbacks to be inheritable outside of some more advanced use cases.
CC @hinthornw
> Update examples to use inheritable callbacks

- docs/evaluation/quickstart.mdx
Two updates:
- Move the first paragraph of `## 2. System to evaluate` to inside py/js tabs & correct links/syntax to be py/js specific
- Updated a link inside the js tab to the js api refs instead of py api refs
> patch: Correct some links from py to js

- src/theme/Feedback.js
Now in GA4 we will have 2 events:
`page_feedback_good` or `page_feedback_bad`
Events by default come with the url
> patch: Update how GA4 events are collected

- docs/evaluation/quickstart.mdx
Running into type errors trying to run the raw docs. This type cast fixes that
> chore(Quickstart evaluation): fix type of formatEvaluatorInputs

- docs/self_hosting/release_notes.mdx
Add release notes for LangSmith v0.4 and adjust older versions to cease referencing SDK and UEX changes.
> Add LS 0.4.x release notes

- docs/self_hosting/release_notes.mdx
Fix premature reference to api/v1 in default path and remove a fragment.
> Remove reference to api/v1

- docs/evaluation/faq/evaluator-implementations.mdx
- docs/monitoring/faq/online_evaluation.mdx
- docs/tracing/concepts.mdx
- docs/tracing/faq/langchain_specific_guides.mdx
- docs/tracing/faq/logging_feedback.mdx
Fixes some typos and formatting issues:
* https://docs.smith.langchain.com/monitoring/faq/online_evaluation#the-prompt-template says inputs and outputs but they’re singular in the screenshot
* https://docs.smith.langchain.com/evaluation/faq/evaluator-implementations#no-labels-criteria-evaluation ## Criteria with labels header has actual hashes and URL reference is broken, same with String distance section
> fix: small typos

- .eslintrc.js
- .github/workflows/format-lint.yml
- docs/evaluation/faq/evaluator-implementations.mdx
- docs/tracing/faq/logging_and_viewing.mdx
- src/components/ClientInstallation.js
- src/components/Hub.js
- src/components/InstructionsWithCode.js
- src/components/QuickStart.js
- src/components/RunTree.js
- src/components/TracingFaq.js
- src/hooks/useColorScheme.js
- src/theme/ColorModeToggle/index.js
- src/theme/SearchBar.js
> ci[minor]: add lint/format to ci

- versioned_docs/version-2.0/how_to_guides/tracing/annotate_code.mdx
Fixes:
```
{ "role": "user", "content": f"Question: {question}
^
SyntaxError: unterminated string literal (detected at line 18)
```
> fix: escape newline in Python code block

- versioned_docs/version-2.0/tutorials/evaluation.mdx
This is literally a one-character change. The name `python` was misspelled as `pyton`, which prevented syntax highlighting.
> Fix typo in code block language name

- vercel.json
We have some links out there to release notes that are now broken since the last redesign, adding back in a redirect for this.
> Add redirect for old release notes

- versioned_docs/version-2.0/how_to_guides/index.md
- versioned_docs/version-2.0/how_to_guides/tracing/distributed_tracing.mdx
Uses the `withRunTree` helper introduced here  https://github.com/langchain-ai/langsmith-sdk/pull/772
> feat(js): add distributed tracing docs

- docusaurus.config.js
- versioned_docs/version-2.0/concepts/tracing/tracing.mdx
- versioned_docs/version-2.0/how_to_guides/tracing/log_llm_trace.mdx
- versioned_docs/version-2.0/reference/index.md
Scalar doesn't allow setting base api url and infers from docs host url
> fix: revert to redoc

- versioned_docs/version-2.0/tutorials/index.md
* fix `Evalutations` to `Evaluations` on Tutorials table of contents/toc
> docs: fix rag evaluations typo on Tutorials TOC

- versioned_docs/version-2.0/how_to_guides/tracing/trace_with_vercel_ai_sdk.mdx
The structure of this method is likely to change once official OTel support drops on Vercel's end and there are a few rough edges in the actual app backend for runs.
> Add beta flag to Vercel tracing docs

- versioned_docs/version-2.0/how_to_guides/index.md
- versioned_docs/version-2.0/how_to_guides/tracing/annotate_code.mdx
- versioned_docs/version-2.0/how_to_guides/tracing/toggle_tracing.mdx
- versioned_docs/version-2.0/how_to_guides/tracing/trace_without_env_vars.mdx
0.1.95 made `trace` respect the `LANGCHAIN_TRACING_V2` env var
> fix: update guidance on tracing without env var in python

- versioned_docs/version-2.0/tutorials/Developers/rag.mdx
While following the RAG evaluation page and doing the tutorial, I got an error `LangSmithNotFoundError: Dataset LCEL-QA not found`.
Since it is necessary to clone the LCEL-QA dataset beforehand in order to use it, I added a command of cloning dataset to the sample code.
Probably related to the following issue: https://github.com/langchain-ai/langsmith-docs/issues/297
> docs: add clone dataset command to rag evaluation tutorial

- docs/tracing/faq/customizing_trace_attributes.mdx
- docs/tracing/faq/logging_and_viewing.mdx
- versioned_docs/version-2.0/how_to_guides/tracing/add_metadata_tags.mdx
- versioned_docs/version-2.0/how_to_guides/tracing/annotate_code.mdx
- versioned_docs/version-2.0/how_to_guides/tracing/log_traces_to_project.mdx
Doing only a post works for child runs and in most scenarios, but we don't block on root submission, so if you're running in lambda, there's a chance the root will never be submitted.
> TSPostPatch

- .github/workflows/spell-check.yml
- versioned_docs/version-2.0/self_hosting/configuration/external_postgres.mdx
- versioned_docs/version-2.0/self_hosting/configuration/external_redis.mdx
- versioned_docs/version-2.0/self_hosting/installation/kubernetes.mdx
- versioned_docs/version-2.0/self_hosting/upgrades.mdx
- versioned_docs/version-2.0/self_hosting/usage.mdx
Few doc cleanups for self-hosted
> docs: self-hosted cleanups

- docs/tracing/faq/langchain_specific_guides.mdx
- src/components/QuickStart.js
On hold until JS docs site has fully updated.
> docs(langchainjs): Update LangChain.js callback backgrounding recommendations

- .gitignore
- docs/reference/authentication_authorization/authentication_methods.mdx
- docs/reference/data_formats/run_data_format.mdx
- docs/self_hosting/faq.mdx
- docs/tutorials/Developers/agents.mdx
- docs/tutorials/Developers/swe-benchmark.mdx
- docusaurus.config.js
- package.json
- src/theme/DocVersionBanner/index.js
- subdirectories/scripts/build_cookbook.py
- subdirectories/scripts/notebook_convert_templates/mdoutput/conf.json
- versioned_docs/version-old/evaluation/migration.mdx
- yarn.lock
This PR upgrades docusaurus from v2 to v3 so we can take advantage of their latest features.
1. **Legacy Cookbook Notebook Converter**: Had to update our old cookbook notebook converter. This logic now has bad rendering in one special case, which is pandas dataframe outputs no longer show up as tables and instead show up as raw text. That's fine, since cookbooks are old, and only left around for posterity
2. **Link syntax changes**: links using ./ instead of ../ were broken. Made fixes where the link checker failed
3. **Special Character Rendering**: Had to move some output of python command into output codeblocks to allow rendering of unicode chars
4. **Old Version Banner**: Our version banner code relied on internal methods in docusaurus v2, so I did some hacking to make them still show …
> fix: upgrade docusaurus to v3.5 to update sitemaps for SEO

- docs/administration/concepts/index.mdx
Remove the reference to August 15, add actual date, and remove old details about API keys.
> Update doc references to api keys

- docs/administration/concepts/index.mdx
section that describes best practices around environment separation
> feat: Best practices guide

- docs/evaluation/how_to_guides/index.md
- docs/observability/how_to_guides/index.md
- docs/observability/how_to_guides/tracing/output_detailed_logs.mdx
Adding docs for already possible behavior to conditionally set the log level for the `langsmith` package
Added the docs in the observability section, but linked to it from both `evaluation` and `observability` how-to guides since it's helpful in both cases.
> feat: change log level in langsmith python package

- docs/observability/how_to_guides/tracing/trace_with_vercel_ai_sdk.mdx
Mirrors changes in https://github.com/vercel/ai/pull/3974
> docs: Update Vercel AI SDK tracing page

- docs/index.mdx
- src/components/QuickStart.js
Main changes: 
- more background on langsmith
- added up front info about what the tutorial covers
> Quick quickstart updates

- docs/observability/how_to_guides/tracing/upload_files_with_traces.mdx
Adding csv files to the attachments example
> adding-csv-to-attachements

- docs/observability/how_to_guides/trace_with_vercel_ai_sdk.mdx
Improve clarity around what format a `runId` can be defined as when using the vercel ai sdk. Currently only UUID is supported.
> docs: Update vercel ai sdk to clarify custom run ids must be uuid

- docs/observability/tutorials/observability.mdx
This PR resolves issue #730 
I reordered the sequence "you help" to "help you" which fixes a grammatical error in the `docs/observability/tutorials/observability.mdx` file. 
Are you able to approve this @angus-langchain ?
> Fix grammatical error in the Observability docs

- docs/evaluation/how_to_guides/fetch_perf_metrics_experiment.mdx
Small fix, a missing ``` is preventing a CodeTabs from rendering correctly.
before:
after:
> chore: fix CodeTabs not rendering

- docs/observability/how_to_guides/log_traces_to_project.mdx
- Updated the official documentation example to use `run_type` instead of `runType`, aligning it with the actual interface.
- The `RunTreeConfig` / `RunTree` interface only permits the `run_type` property, so the discrepancy between the docs and the code causes type errors.
- This is a documentation-only change; no additional build or code verification is required.
> fix(docs): use run_type instead of runType in TS example

- docs/self_hosting/troubleshooting.mdx
Linking to our new k8s debugger script in our docs. Also, adding a section about getting and analyzing a HAR file for browser errors.
Testing:
Validated the docs page looks as expected here: https://langsmith-docs-gdt6jk87j-langchain.vercel.app/self_hosting/troubleshooting
> docs: Added more troubleshooting tips and link to a k8s guide

- docs/observability/how_to_guides/trace_langchain_with_otel.mdx
1. Added "info" banner about Hybrid Tracing
> Since langsmith ≥ 0.4.1, 
> setting LANGSMITH_OTEL_ENABLED=true automatically adds a LangSmith OTEK exporter and respects any existing OpenTelemetry TracerProvider or standard OTEL environment variables you configure.
> 
> This means enabling LANGSMITH_OTEL_ENABLED will by default send traces to both LangSmith and your OTEL enpoint (if you have global trace provider initiazlied). No extra code is needed for fan-out. 
> 
And 
> To disable the hybrid behavior after 0.4.1 and send traces only to your OTEL endpoint and exclude sending to LangSmith, add an additional env var:
> 
> LANGSMITH_OTEL_ONLY = "true"
> 
2. This page is pretty long so i added a quick preview
3. I think Distributed Tracing section is an advanced usecase and a less frequent …
> doc: Update otel page with Hybrid Tracing info

- docs/observability/how_to_guides/data_export.mdx
We now support filtering runs with our query language when running a bulk export job. This PR adds documentation to record the same.
> add docs for filtering bulk export runs

- docs/self_hosting/configuration/mirroring_images.mdx
- docs/self_hosting/configuration/using_an_existing_secret.mdx
- docs/self_hosting/mirroring_images.mdx
> docs: add mirroring images guide

- docs/self_hosting/installation/kubernetes.mdx
This week we release AWS terraform modules. Lets link those in our LS self hosted installation docs to make installation easier.
> docs: Link our newly created terraform modules to our LS docs

- docs/self_hosting/configuration/blob_storage.mdx
This is another way to allow secure connection to S3 without enabling public access. This is what we currently do in our public TF modules.
Docs look as expected:
> docs: Add VPCE auth method for S3 connection
