langchain-ai/langsmith-docs

docs/index.mdx
=> Production Support Form

docs/index.mdx, docs/tracing/use-cases/export-runs/local.mdx
=> Fix code rendering

src/components/QuickStart.js
Split up code block between "if process.env" is accessible or not (confusing otherwise)
Switch priority of 'traceable' decorator
=> Update TS Quickstart

src/components/TracingFaq.js
=> Fix run collector example

subdirectories/scripts/build_cookbook.py, subdirectories/scripts/requirements.txt
=> Update Cookbook References

docs/evaluation/evaluator-implementations.mdx
- Add missing `run_on_dataset` function call
=> Fix missing function call part

docs/index.mdx, src/components/QuickStart.js
Some initial edits based on https://www.infoworld.com/article/3708628/what-is-langsmith-tracing-and-debugging-for-llms.html
=> Infoworld blog post fixes

docs/index.mdx
Hi!
Noticed this minor dead link, updated!
Signed-off-by: Prince Mendiratta <prince.mendi@gmail.com>
=> :books: smith: update walkthrough notebook link

docs/evaluation/datasets.mdx
Probably the simplest PR you can possibly have 😃
=> Wrong paran name for dataset_name in docs

docs/tracing/integrations/typescript.mdx
=> Update JS docs to use wrapOpenAI

docs/pricing.mdx, docs/self_hosting/docker.mdx, docs/self_hosting/kubernetes.mdx, docs/self_hosting/release_notes.mdx
Adding release notes for 0.3.x
Fixing blurb re: enterprise license
Tweak SSO verbiage
=> Fix enterprise license language

docs/tracing/integrations/typescript.mdx
=> Add TS wrapSDK docs

docs/tracing/faq/index.mdx, docs/tracing/faq/langchain_specific_guides.mdx, docs/tracing/faq/logging_feedback.mdx, docs/tracing/faq/querying_traces.mdx, docs/user_guide.mdx
To include trace and tree filters
=> Update Query Guide

docs/tracing/faq/querying_traces.mdx
| | |
|------|------|
| before | ![image](https://github.com/langchain-ai/langsmith-docs/assets/46789226/7acef72f-b914-442e-94a5-f818fd44b154) |
| after | ![image](https://github.com/langchain-ai/langsmith-docs/assets/46789226/e09a9b45-3a20-4ef0-a4ee-43109d757a4a) |
=> [patch]: Update trace query API section into a table

docs/pricing.mdx
Add details about the new startup plan.
=> Add startup plan details and links to contact form.

package.json, src/components/InstructionsWithCode.js, yarn.lock
@agola11 couldn't figure it out but this uses a library I'm familiar with
=> Render markdown using marked and DOMPurify

docs/monitoring/faq/webhooks.mdx
=> Fixed typo in webhooks.mdx

versioned_docs/version-2.0/how_to_guides/tracing/trace_generator_functions.mdx
TS seems to not work rn though
=> Add tracing generators doc

docs/evaluation/faq/regression-testing.mdx, docs/evaluation/index.mdx, docs/index.mdx, docs/monitoring/concepts.mdx, docs/monitoring/faq/filter.mdx, docs/monitoring/faq/monitoring.mdx, docs/monitoring/faq/online_evaluation.mdx, docs/monitoring/index.mdx, docs/monitoring/quickstart.mdx, docs/tracing/concepts.mdx, docs/tracing/faq/customizing_trace_attributes.mdx, docs/tracing/faq/logging_and_viewing.mdx, docs/tracing/faq/logging_feedback.mdx, docs/tracing/index.mdx, docs/tracing/integrations/python.mdx, docs/tracing/quick_start.mdx, docs/tracing/use_cases/summarize-usage.mdx, docs/tracing/use_cases/track-sentiment.mdx, docusaurus.config.js, versioned_docs/version-2.0/how_to_guides/tracing/add_metadata_tags.mdx, versioned_docs/version-2.0/how_to_guides/tracing/annotate_code.mdx, versioned_docs/version-2.0/how_to_guides/tracing/log_traces_to_project.mdx, versioned_docs/version-2.0/index.mdx, versioned_docs/version-2.0/reference/data_formats/feedback_data_format.mdx, versioned_docs/version-2.0/tutorials/evaluation.mdx
Reverts langchain-ai/langsmith-docs#220
=> Revert "flip docs to new version"

docs/evaluation/faq/regression-testing.mdx, docs/evaluation/index.mdx, docs/index.mdx, docs/monitoring/concepts.mdx, docs/monitoring/faq/filter.mdx, docs/monitoring/faq/monitoring.mdx, docs/monitoring/faq/online_evaluation.mdx, docs/monitoring/index.mdx, docs/monitoring/quickstart.mdx, docs/tracing/concepts.mdx, docs/tracing/faq/customizing_trace_attributes.mdx, docs/tracing/faq/logging_and_viewing.mdx, docs/tracing/faq/logging_feedback.mdx, docs/tracing/index.mdx, docs/tracing/integrations/python.mdx, docs/tracing/quick_start.mdx, docs/tracing/use_cases/summarize-usage.mdx, docs/tracing/use_cases/track-sentiment.mdx, docusaurus.config.js, src/theme/DocVersionBanner/index.js, vercel.json, versioned_docs/version-2.0/how_to_guides/tracing/add_metadata_tags.mdx, versioned_docs/version-2.0/how_to_guides/tracing/annotate_code.mdx, versioned_docs/version-2.0/how_to_guides/tracing/log_traces_to_project.mdx, versioned_docs/version-2.0/index.mdx, versioned_docs/version-2.0/reference/data_formats/feedback_data_format.mdx, versioned_docs/version-2.0/tutorials/evaluation.mdx
Reverts langchain-ai/langsmith-docs#224
=> flip docs to new version (correctly)

versioned_docs/version-2.0/concepts/tracing/tracing.mdx
Draft pending an exact date and timestamp.
=> Add details to docs about data retention

versioned_docs/version-2.0/concepts/tracing/tracing.mdx
Clarify how to retain your trace inputs/outputs longer than 400 days based on feedback here https://github.com/langchain-ai/langsmith-docs/issues/267
=> Add to dataset to retain inputs and outputs

versioned_docs/version-2.0/pricing.mdx
=> Tweak security certification language

versioned_docs/version-2.0/how_to_guides/datasets/index.mdx, versioned_docs/version-2.0/how_to_guides/evaluation/index.mdx, versioned_docs/version-2.0/how_to_guides/human_feedback/index.mdx, versioned_docs/version-2.0/how_to_guides/monitoring/index.mdx, versioned_docs/version-2.0/how_to_guides/playground/index.mdx, versioned_docs/version-2.0/how_to_guides/prompts/index.mdx, versioned_docs/version-2.0/how_to_guides/setup/index.mdx, versioned_docs/version-2.0/how_to_guides/tracing/index.mdx
=> Adds linkable index pages to how-to guides

versioned_docs/version-2.0/how_to_guides/index.md, versioned_docs/version-2.0/how_to_guides/tracing/mask_inputs_outputs.mdx
Will be released in JS@0.1.33, Python@0.1.81
=> feat(tracing): add masking i/o docs

versioned_docs/version-2.0/how_to_guides/tracing/trace_with_langchain.mdx
=> Fix typo in interoperability docs

versioned_docs/version-2.0/concepts/admin/admin.mdx, versioned_docs/version-2.0/self_hosting/configuration/index.mdx, versioned_docs/version-2.0/self_hosting/configuration/user_management.mdx
=> chore: docs for inviting to org at workspace level FF

docs/evaluation/faq/unit-testing.mdx, versioned_docs/version-2.0/tutorials/Developers/agents.mdx
Also closes: https://github.com/langchain-ai/langsmith-sdk/issues/868
=> Nits on evals docs

versioned_docs/version-2.0/how_to_guides/datasets/manage_datasets_programmatically.mdx, versioned_docs/version-2.0/how_to_guides/index.md
also includes the new bulk update endpoint
=> add docs for updating examples

versioned_docs/version-2.0/how_to_guides/tracing/trace_with_langchain.mdx
Dependant on https://github.com/langchain-ai/langsmith-sdk/pull/874 and https://github.com/langchain-ai/langchainjs/pull/5992
=> feat(js): add info and disclaimer about auto-tracing from LC to LS

src/components/InstructionsWithCode.js, src/components/QuickStart.js, src/css/custom.css, versioned_docs/version-2.0/how_to_guides/tracing/trace_with_langchain.mdx
=> Add note on backgrounding callbacks to configuration instructions for JS

docusaurus.config.js, package.json, yarn.lock
This reverts commit 2952c61f66fa98e76fc539e3e6a0e9c782d28472, reversing changes made to 47c98586b2058f827438721d7c7513f23a984704.
=> Revert "fix: upgrade scalar (#320)"

versioned_docs/version-2.0/self_hosting/release_notes.mdx
PR for Release Notes for LS Docs for the v0.7 SH release.
=> Self-Hosted Release Notes for v0.7

versioned_docs/version-2.0/self_hosting/scripts/generate_clickhouse_stats.mdx, versioned_docs/version-2.0/self_hosting/scripts/index.md
Fixes a bad link in the sidebar
=> Update docs links for scripts

docs/administration/how_to_guides/organization_management/set_up_saml_sso.mdx
=> fix: nested notes format

docs/observability/how_to_guides/tracing/trace_with_opentelemetry.mdx
=> fix: otel typos

docs/evaluation/how_to_guides/pytest.mdx, docs/evaluation/tutorials/testing.mdx
Reflect https://github.com/langchain-ai/langsmith-sdk/pull/1472
Merge after release
=> docs: Update pytest table output

docs/observability/how_to_guides/trace_with_opentelemetry.mdx
=> Add otel mapping to docs

docs/evaluation/how_to_guides/vitest_jest.mdx
Addresses https://github.com/langchain-ai/langsmith-sdk/issues/1639
=> docs: Adds warning note about JSDom with Vitest

docs/prompt_engineering/how_to_guides/index.md
=> docs: link to prompt tags from how to guides overview

docs/evaluation/tutorials/rag.mdx
Typos made it hard to copy paste and use without syntax correcting manually
=> Fixed some minor Typos

docs/self_hosting/configuration/using_an_existing_secret.mdx
=> docs: add existing secrets guide

docs/self_hosting/installation/kubernetes.mdx, docs/self_hosting/upgrades.mdx
=> docs: add easier command to fetch versions, some docs cleanups.

.prettierignore, docs/observability/how_to_guides/threads.mdx
CC @lnhsingh something is wrong with our formatter
=> Fix indents for howto guide

docs/self_hosting/configuration/external_postgres.mdx
Clarify the wording around support for postgres poolers per the discussion in #844
=> Clarify pgbouncer & pooler support

docs/observability/how_to_guides/trace_with_vercel_ai_sdk.mdx
Customize run name and metadata
=> docs: Add more AI SDK docs

docs/self_hosting/usage.mdx
=> docs: add truststore section in usage

docs/observability/how_to_guides/alerts_pagerduty.mdx, docs/observability/how_to_guides/data_export.mdx
=> chore: bump scheduled export version

docs/self_hosting/configuration/ttl.mdx
Queue.extraEnv -> Queue.deployment.extraEnv
=> Fix queue helm values in TTL docs
